# Use the official Node.js 14 image
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port your app runs on
EXPOSE 3000
EXPOSE 3001
 
# Start the application
# CMD if [ "$NODE_ENV" = "test" ]; then npx json-server --watch db.json --port 3001 & npm test; else npm run start & npx json-server --watch db.json --port 3001; fi
CMD npm run start & npx json-server --watch db.json --port 3001

